# packages/logger/Dockerfile.dev
FROM node:22-alpine

WORKDIR /usr/src/app

# Copia package.json e instala depêndencias
COPY package*.json ./
RUN npm ci

# Copia todo o código
COPY . .

EXPOSE 3000

# Usa start:dev (ajuste se teu package.json usar outro script)
CMD ["npm", "run", "start:dev"]